version: "3.1"

services:
  from-source:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ORIGIN=https://transport.cm
    env_file:
      - .env
    restart: on-failure
    ports:
      - 3000:3000

  from-image:
    image: ghcr.io/dipandaaser/transport-prices:latest
    environment:
      - ORIGIN=https://transport.cm
    env_file:
      - .env
    restart: on-failure
    ports:
      - 3000:3000
