version: "3.1"

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # - ORIGIN=https://werr.cm
    env_file:
      - .env
    restart: on-failure
    ports:
      - 3000:3000
