name: Deploy

on: workflow_dispatch

jobs:
   deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Remote command
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.SSHPORT }}
          script: |
            cd ${{ secrets.PROJECTLOCATION }}
            make docker-down
            make docker-up